[package]
name = "client"
version = "0.1.0"
authors = ["Tomasz Mikus <mikus.tomasz@gmail.com>"]
edition = "2021"

[dependencies]
blip_buf = ">=0.1.3"
clap = "4"
#cpal = "0.15" # This causes an error on Raspberry Pi
glium = "0.36"
#winit = "0.29" # This doesn't like Raspberry Pi too
